apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-backend
  namespace: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecom-backend
  template:
    metadata:
      labels:
        app: ecom-backend
    spec:
      containers:
      - name: backend
        image: mcr.microsoft.com/azuredocs/aci-helloworld:latest
        ports:
        - containerPort: 80
